
domain: "https://sample.atlassian.net"
username: "<USERNAME>"
password: "<PASSWORD>"
projectKey: "PROJECT_KEY"
#Optional, if empty logged as Bug
issueType: "Bug"

#http timeouts
connectTimeout: 10000
socketTimeout: 10000

proxy:
 uri:
 user:
 password:


