
domain: "https://appdx-dev.atlassian.net"
projectKey: "EXT"
#Optional, if empty logged as Bug
issueType: "Bug"

username: "admin"
password: "p@ssword123"
#encryptedPassword:

#http timeouts
connectTimeout: 10000
socketTimeout: 10000

#proxy details, either provide proxyUri or provide proxyHost and proxyPort.
proxy:
 uri:
 user:
 password:
 #encryptedPassword:


