
domain: "https://sample.atlassian.net"
username: "<USERNAME>"
password: "<PASSWORD>"
#encryptedPassword: ""

#encryptionKey: ""

projectKey: "PROJECT_KEY"
#Optional, if empty logged as Bug
issueType: "Bug"
#priorityNotRequired: true
#component: "Product Extension"

#http timeouts
connectTimeout: 10000
socketTimeout: 10000

proxy:
 uri: ""
 user: ""
 password: ""
 #encryptedPassword: ""


